---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: system-upgrade
  namespace: flux-system
spec:
  interval: 30m
  ref:
    tag: v0.13.2
  url: https://github.com/rancher/system-upgrade-controller
