---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: tigera-operator
  namespace: tigera-operator
spec:
  interval: 15m
  chart:
    spec:
      chart: tigera-operator
      version: v3.28.0
      sourceRef:
        kind: HelmRepository
        name: calico
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    installation:
      enabled: true
      registry: quay.io
      imagePath: calico
      calicoNetwork:
        # Note: The ipPools section cannot be modified post-install.
        ipPools:
          - blockSize: 26
            cidr: 10.42.0.0/16
            encapsulation: VXLANCrossSubnet
            natOutgoing: Enabled
            nodeSelector: all()
          - blockSize: 122
            cidr: 2001:cafe:42:0::/56
            encapsulation: None
            natOutgoing: Enabled
            nodeSelector: all()
      nodeMetricsPort: 9091
      typhaMetricsPort: 9093
