---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: recyclarr
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.3.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/recyclarr/recyclarr
              tag: 6.0.2
            probes:
              liveness: &probes
                enabled: false
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: &port 80
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
    env:
      TZ: "Australia/Perth"
    envFrom:
      - secretRef:
          name: recyclarr-secrets
    service:
      main:
        enabled: false
    # ingress:
    #   main:
    #     enabled: true
    #     ingressClassName: "traefik"
    #     annotations:
    #       cert-manager.io/cluster-issuer: "letsencrypt-production"
    #       traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    #     hosts:
    #       - host: "recyclarr.${SECRET_DOMAIN}"
    #         paths:
    #           - path: /
    #             pathType: Prefix
    #     tls:
    #       - hosts:
    #           - "recyclarr.${SECRET_DOMAIN}"
    #         secretName: "recyclarr-${SECRET_DOMAIN//./-}-tls"
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
    persistence:
      config:
        enabled: true
        existingClaim: recyclarr-config
        mountPath: /config
      config-file:
        enabled: true
        type: configMap
        name: recyclarr-configmap
        subPath: recyclarr.yml
        mountPath: /config/recyclarr.yml
        readOnly: true
    resources:
      requests:
        memory: 50Mi
        cpu: 10m
      limits:
        memory: 200Mi
