---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: apache-airflow
  namespace: orchestration
spec:
  chart:
    spec:
      # renovate: registryUrl=https://airflow.apache.org
      chart: airflow
      version: 1.13.1
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: apache-airflow-charts
        namespace: flux-system

  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  interval: 1m0s

  values:
    webserverSecretKeySecretName: my-webserver-secret

    env:
      - name: TZ
        value: Australia/Perth
    ingress:
      web:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        enabled: true
        hosts:
          - name: "airflow.${SECRET_DOMAIN}"
            tls:
              secretName: "airflow-${SECRET_DOMAIN//./-}-tls"
              enabled: true
        ingressClassName: traefik
    createUserJob:
      useHelmHooks: false
      applyCustomEnv: false
    migrateDatabaseJob:
      useHelmHooks: false
      applyCustomEnv: false

    webserver:
      service:
        type: NodePort

      livenessProbe:
        initialDelaySeconds: 10
        timeoutSeconds: 100
        failureThreshold: 5
        periodSeconds: 600
    dags:
      persistence:
        enabled: true
        existingClaim: airflow-dags
      gitSync:
        enabled: false
