apiVersion: v1
data:
    webserver-secret-key: ENC[AES256_GCM,data:hzpR39rOgg6k4dGfrISUoWYMxA2gp+UBZp1Ip2OsvxaOU7f2y0Jtn9dZStU=,iv:iCj4cmHrOylllxtt6g7qJU7UHNkdjodpGlwrkRmOJWI=,tag:4zl8EHpezPM4zrwbY8z1Ig==,type:str]
kind: Secret
metadata:
    name: my-webserver-secret
    namespace: orchestration
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jvwt3fts5200w0fgtdjv72v9qltsgxyjulcdyvs52v2ajpjdzd4qvnuav9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4MWRhN3RqZVFUdDlWdUhq
            TkpuNWw4aUpnWG5YVlZFQVlnUkFUbFFITkVBCkE1Z3ZudGNEakZVZll3ZVN3RHZZ
            bmhJVW5leWVQKzJMbUxPeXR2ODBjTlUKLS0tIE5saE5ZVVFGSHkzVE1qZXZVV1lG
            Q0NkbnFZd0YrS0p4YnBMWThhVytUT0kKiKACGifsoKdx2Bo+JNqZM3JHj7acZW1x
            HS0E2Y2dBT82yKMXgy1Ka9mkgnEAG6Tp/WgR5igY3G93T0xE4hwVxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-17T10:02:38Z"
    mac: ENC[AES256_GCM,data:VlrjpDnWwT8taRIdu8CkPLi5eSYrcJrORHlEv9rNhiQdaCMDilpC0auY02/ay/dyq0WTaCzGFHI2pq0Z7YekYEbd4fK20yBvsSosQ0tUzZnxf/FZlet/YDPEFG3oOP2z/ybQkDFW1U5QoKE8HN//03VDkZDBmyhDTiKMkl1Kvhc=,iv:ZdtxEbZlfAHtVM3nwvXEPtDY4GJ6s90ax/nVk6x64IU=,tag:9llZm9e1TYx4CvkJJo6mOQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
