---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-tigera-operator
  namespace: flux-system
spec:
  path: ./cluster/apps/networking/calico/tigera-operator/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: tigera-operator
      namespace: tigera-operator
  interval: 15m
  retryInterval: 1m
  timeout: 3m
