---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: trivy-operator
  namespace: monitoring
spec:
  chart:
    spec:
      # renovate: registryUrl=https://aquasecurity.github.io/helm-charts/
      chart: trivy-operator
      version: 0.20.4
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: aquasecurity-charts
        namespace: flux-system
  interval: 10m0s
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    trivy:
      ignoreUnfixed: true

    trivyOperator:
      scanJobCompressLogs: true

    operator:
      scanJobsConcurrentLimit: 4

    env:
      - name: TZ
        value: Australia/Perth
