---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system-upgrade
  namespace: system-upgrade
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: system-upgrade
  targetNamspace: system-upgrade
  images:
    - name: rancher/system-upgrade-controller
      newTag: v0.13.2
