---
apiVersion: v1
kind: Namespace
metadata:
  name: databases
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: kafka
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
