---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: influxdb2
  namespace: monitoring
spec:
  interval: 5m0s
  chart:
    spec:
      # renovate: registryUrl=https://helm.influxdata.com/
      chart: influxdb2
      version: 2.1.1
      sourceRef:
        kind: HelmRepository
        name: influxdata-charts
        namespace: flux-system
  values:
    image:
      tag: 2.3.0-alpine
      pullPolicy: IfNotPresent

    env:
      - name: TZ
        value: Australia/Perth

    persistence:
      config:
        enabled: true
        StorageClass: nfs-csi

    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      hostname: "influxdb2.${SECRET_DOMAIN}"
      tls: true
      secretName: "influxdb2-${SECRET_DOMAIN//./-}-tls"
