---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-cache
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-csi
