---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-csi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-cache
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-csi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-ugreen
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfc-ugreen

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-cache-ugreen
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfc-ugreen
