---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: kube-system
spec:
  chart:
    spec:
      # renovate: registryUrl=https://helm.releases.hashicorp.com
      chart: vault
      version: 0.24.1
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system

  interval: 10m0s

  values:
    server:
      dataStorage:
        accessMode: ReadWriteOnce
        enabled: true
        size: 100Mi
        storageClass: nfs-csi
