---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: kube-system
spec:
  chart:
    spec:
      # renovate: registryUrl=https://helm.releases.hashicorp.com
      chart: vault
      version: 0.30.0
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system

  interval: 10m0s

  values:
    server:
      dataStorage:
        accessMode: ReadWriteOnce
        enabled: true
        size: 100Mi
        storageClass: nfs-csi

      ingress:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        pathType: Prefix
        hosts:
          - host: &host "vault.${SECRET_DOMAIN}"
        tls:
          - hosts:
              - *host
            secretName: "vault-${SECRET_DOMAIN//./-}-tls"

      service:
        type: ClusterIP
        port: 8200
        externalPort: 80
        clusterPort: 8201
