apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-secret
    namespace: networking
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:fU1DiglJ7TCn3SF7kCtaqRfp4RhjV02xJ9yHG5vicuCfJO6FMhoxY//E+Q+vZ6jN3eUOUTku2CuDJ3b+T1NlbwMOYxfvkkXZsXL695BXuhYcj4PKMMWT31cSRtaXIXS1LVTppa9Zu03G7f7zVl5BERg86s5mRG9FoROAIK6Nt4OozK5ZPsGgOkXZ0QPEUy2hOhkW64SXaDhl4LJTtooV8H8pa3HujolZwF3TliLEhu6MIbG7K2rkkQ==,iv:m0874D3Up2eBrq3fZrb9xQmb+sUHIb0dMeCtGne+GmM=,tag:bXqmbDge7yISmY2a8d2ouw==,type:str]
    TUNNEL_ID: ENC[AES256_GCM,data:XwNymrCUCP9e5qIjUUwFfBbPSTTb1rFn5oUPHz/0mGskJrYj,iv:amWOKjXFD/9Y70SpM/k0mRRmMWJyGwUypaDZgcEr2+M=,tag:GTcCUb0cOSLe503SBBJ+VQ==,type:str]
sops:
    age:
        - recipient: age1jvwt3fts5200w0fgtdjv72v9qltsgxyjulcdyvs52v2ajpjdzd4qvnuav9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhN3JjZUFMM3M3bDM0aHlG
            alJXQTJLanF6ekRZRXV4YWlXKzFvM3hGYVMwCnBWSTdleW9vYnY4TUF6WTAxWi9z
            dW1ZL1Z5bWxFSGNVREszQU51L0kxZnMKLS0tIGI4YmsxY0FJYnNSM1hQdlZUck1F
            ekp3dFFyYms4N0hScW8ybjJOb3M1SzgKr+NwxzvZf5N+PvMHRgXJYcBkKSNGxeY1
            9ufxzdEg0FQWgBBM/GC0uakJrd3i0ntVGZHk1tA7moXZUkDe2CVrxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-19T16:05:31Z"
    mac: ENC[AES256_GCM,data:1VodjGTJLfMZG/Fg1/6+Y8aN17v6M44NovEZYl37RRqXTTQqqMbXJGwy5hQbNztMqZ7krVWAKwzs1TwcQdCQRlM4mTLcv4wTyNz2o0i4UaYtaluBP3251URh6pnQ5e37P8t9VxkHS26Eb1jsRN46sIK5bmdhJuOpsZMOBMdT1mc=,iv:xRM66Obt05wx1lYL+IYKx7MaNHmZE4bsc/GhNDQxDFs=,tag:2W/06x56OOcdh+fY4lii2Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
