apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-secret
    namespace: networking
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:7YOHW0XLTLXU3azsPv2oA22K5HbdZrmZkxq/3BZVNo4xf3/8CjM+s8O5iT+FGZnZMEp6jOCQKUJlrTUvPzWn5qtMPwBdLEWIzgnrVmcQZAidzJtDETGQxgiO2M50gkZmb1CMLyAKznO9xprRN2C/4aPaW23MfgacWd9q96rBnLuBsm8EDfqYSrUV0JP6XAQKLXRp5hw0O5fxoNMgVAuQsCUyOD6add0rjcKPilnkovbIbSLEsc78gA==,iv:4LES2s88dTVdFvHjFRO8cDlNj+ARf8inifx99SWIbtM=,tag:obdnhybtcMMU5uVi27zx3Q==,type:str]
sops:
    age:
        - recipient: age1jvwt3fts5200w0fgtdjv72v9qltsgxyjulcdyvs52v2ajpjdzd4qvnuav9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2Q21EY0dmUDVGdk1OamFK
            d0N6VFppbHhNbi9peUJzeXdSaW5IYTZ4Znc4Cno4M09wczNsVUtYUkhGS21IWWNL
            Z2cxeDJPWi94elRLa0xWZDJqMVNzTDgKLS0tIGZ1TFFsU2RMUUtSMmI5Ukx4aWhQ
            dFlLU2tpcFQ0Q2lZelNDekRCdWtjTTQKV41BKWo99aq9b4P16g5ptym+6W7GQKZW
            iQgr8t9NfqDxBdV8G+Nbs/mvOy1yft3/miKEC1FtEjYbsFpjaIQPNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-19T16:52:09Z"
    mac: ENC[AES256_GCM,data:cZK4bXcTL7GLPUYdRk9JE3OX46er2Sa8vlHeqmifQTcZm0y8G5rwr57XtlMhdG1OxCVygxt/4FyZyUuZIYvmL/ZDOZni5UC6FbMJZRoeIB9HmD2wcl5+B08fg6tIBgJ3k0pz6215JTRR6nIOCocMIL3HTIWp4mtPDpoBlMRCivs=,iv:hL3HngxNh1ihAoMTobRMdQBOw8gkWO0y/9xUdhrBvMo=,tag:rIZZ5DYF2mhd9wB+6yn72A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-id-secret
    namespace: flux-system
stringData:
    CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:BsmIWzolP72HWMjgL6wgxZ0wVQ0Q9tD+4s9gAkUUh5b5pTn2,iv:ItRMDQMzFBXLd1o1S3mRctuT9TvOzE8VfCMmHDQwLNQ=,tag:2fMh/O3jU5T8vjJI/vQ58w==,type:str]
sops:
    age:
        - recipient: age1jvwt3fts5200w0fgtdjv72v9qltsgxyjulcdyvs52v2ajpjdzd4qvnuav9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2Q21EY0dmUDVGdk1OamFK
            d0N6VFppbHhNbi9peUJzeXdSaW5IYTZ4Znc4Cno4M09wczNsVUtYUkhGS21IWWNL
            Z2cxeDJPWi94elRLa0xWZDJqMVNzTDgKLS0tIGZ1TFFsU2RMUUtSMmI5Ukx4aWhQ
            dFlLU2tpcFQ0Q2lZelNDekRCdWtjTTQKV41BKWo99aq9b4P16g5ptym+6W7GQKZW
            iQgr8t9NfqDxBdV8G+Nbs/mvOy1yft3/miKEC1FtEjYbsFpjaIQPNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-19T16:52:09Z"
    mac: ENC[AES256_GCM,data:cZK4bXcTL7GLPUYdRk9JE3OX46er2Sa8vlHeqmifQTcZm0y8G5rwr57XtlMhdG1OxCVygxt/4FyZyUuZIYvmL/ZDOZni5UC6FbMJZRoeIB9HmD2wcl5+B08fg6tIBgJ3k0pz6215JTRR6nIOCocMIL3HTIWp4mtPDpoBlMRCivs=,iv:hL3HngxNh1ihAoMTobRMdQBOw8gkWO0y/9xUdhrBvMo=,tag:rIZZ5DYF2mhd9wB+6yn72A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
