apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-secret
    namespace: networking
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:+9KZyzlVrOusSlAH6DK2mdTkmu+2UqaxHjlq2mLdni//Nto5xYJ235vd0g8rGHUO7rfy0cGN7wdADnwmrXsEFghz+7DNk0EjgRl8G7y7kyGHlApztFP0czdow5MNbBrb0f3J0TR44muqvl39lsmp8rbFTPS2cPpFckY7fgjT+P+zeidEGiPEnnJzmHMtfy8MqeNLwKa7FQ1cuHGompo33sQHHbsc2/xEaadFSVYY3gF8wW5cwGsaTA==,iv:EOHdkTAk6abogUpHUgg04MckWPL6+8H6FJSzTODEO60=,tag:TVD4rBSOX7kdwU5uM8cKvg==,type:str]
    CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:wlvtF+C6Q+U/0m27lTNEtaQ2mDbEiRUOqW74nc6XESZAlmvA,iv:VGdwGIBW1uLjB3bfNsYIfJq1TbU8V2RmoJlZLrco4NY=,tag:/jO5wgzJTbdUaUGHDE7O0A==,type:str]
sops:
    age:
        - recipient: age1jvwt3fts5200w0fgtdjv72v9qltsgxyjulcdyvs52v2ajpjdzd4qvnuav9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4MnBodWxKTndicDJ2OHFM
            TjBJMTMwb2NrTHU1NjhNSzllSHJOVU1HeEVFCnA3NUF5RUpPVXhTR1VBbWFDaGZP
            dS9Qb291NTBzSjZOUGxTNlF2YkJYakEKLS0tIHExSnk5VHBJSUVlazR0S25pOFF4
            dGYrTnd0WXF0SURpQmRrcWZVK2tid1UKNpyNdSX3/dBvPUfwAY9+pUoOc2nmVfyl
            0ERWLfyyE9YvcbZONzeP4WuMO9dA/BChuReDQ9WgCsYlNUkbS27bdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-19T16:37:32Z"
    mac: ENC[AES256_GCM,data:xk4YRwipHBeV6MvYc7IMTC6K0m/2gBHIffJnIg7/1+krrC4bTvciP0MzK0dOFKcryLuHupJZT/WdRakN/pcGKOD7BMf8gzvsQwEhASIhsBf8+Op9FIT037zjKfKuYeOCHgOIslpoNmaHP7dzdYzrPVT8yCIXdp4Dxlq/BGmFcGE=,iv:k6KtHhjbXHwEiZKXekl1Er89PojV8HX4sUcr6q/dlfs=,tag:fvwfvArsoCBWC5UQKZhBkg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
