---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: jhub
  namespace: jhub
spec:
  chart:
    spec:
      # renovate: registryUrl=https://hub.jupyter.org/helm-chart/
      chart: jupyterhub
      version: 3.3.2
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: z2jh-charts
        namespace: flux-system
  interval: 10m0s
  values:
    proxy:
      service:
        type: LoadBalancer
        annotations:
          metallb.universe.tf/loadBalancerIPs: 192.168.86.204
    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      hosts:
        - &host "jupyter-ir.${SECRET_DOMAIN}"
      tls:
        - hosts:
            - *host
          secretName: "jupyter-ir-${SECRET_DOMAIN//./-}-tls"
    scheduling:
      userScheduler:
        enabled: false
    singleuser:
      extraEnv:
        TZ: Australia/Perth
      image:
        name: jupyter/minimal-notebook
        tag: 6cc4a8596a0b
      memory:
        guarantee: 1G
        limit: 2G
      networkPolicy:
        egressAllowRules:
          privateIPs: true
      profileList:
        - default: true
          description: "To avoid too much bells and whistles: Python."
          display_name: Minimal environment
        - description: "If you want scipy."
          display_name: Scipy environment
          kubespawner_override:
            image: ghcr.io/shadowkrusha/scipy:sha-3d2b798
        - description:
            "If you want the additional bells and whistles: Python, R, and
            Julia."
          display_name: Datascience environment
          kubespawner_override:
            image: ghcr.io/shadowkrusha/datascience:sha-3d2b798
        - description: The Jupyter Stacks spark image!
          display_name: Spark environment
          kubespawner_override:
            image: jupyter/all-spark-notebook:6cc4a8596a0b
        - description: scipy & tensorflow
          display_name: Tensorflow environment
          kubespawner_override:
            image: jupyter/tensorflow-notebook:2023-07-11
        - description: SingleUser Image 4
          display_name: Jupyterhub Single User Image
          kubespawner_override:
            image: jupyterhub/singleuser:4.0.2
        - description: Z2JH Base image
          display_name: Jupyterhub Base Image
          kubespawner_override:
            image: jupyterhub/k8s-singleuser-sample:3.0.1-0.dev.git.6287.hbfb05cd6
        - description: Datascience Python 3.10
          display_name: Datascience Python 3.10
          kubespawner_override:
            image: jupyter/datascience-notebook:python-3.10
        - description: Datascience Python 3.8
          display_name: Datascience Python 3.8
          kubespawner_override:
            image: jupyter/datascience-notebook:python-3.8
      storage:
        dynamic:
          storageClass: nfs-csi
        extraVolumeMounts:
          - mountPath: /dev/shm
            name: shm-volume
        extraVolumes:
          - emptyDir:
              medium: Memory
            name: shm-volume
