---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-local-path-provisioner
  namespace: flux-system
spec:
  path: ./cluster/apps/kube-system/local-path-provisioner/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: local-path-provisioner
      namespace: kube-system
  interval: 15m
  retryInterval: 1m
  timeout: 3m
