apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:CFpd4E0ql5phBhKcIEd8mw==,iv:I7t+rRYpmiqbIaJ2dVOg7hj4QiGoNuJK4+ejqNzIGQ4=,tag:M/NjKSfbj2gsdnKLI11YQg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:bFhuHU3wuco3Thvp778xePm0UCk=,iv:tXYJ2anpj4cSCTJqTQhF1HtoNv1Jd+Aydc1K0FR1SuA=,tag:k/uFyR5ybzgdDUkiWEkriA==,type:str]
    CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:mdBtg9WiMTPkMw2pq/pGsYmmqJFkv7ysySW7Mg57evAeO/VF,iv:sAIKS9JpOD/8YehZUj1O4Tc41/kT32MxW217yhjvXTg=,tag:5lm5HUpISknKY0dVD0UNTw==,type:str]
sops:
    age:
        - recipient: age1jvwt3fts5200w0fgtdjv72v9qltsgxyjulcdyvs52v2ajpjdzd4qvnuav9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3YzdLbnRWTlAvMlRwZGZx
            SFlOa01FMEZFeE0xcWlnWER4a21DTUxHVGwwCk4zSGVldGIyM1NvN3RCKzJNNml0
            U3FCd29XdktRM1BGOWFoMEF2ZE9RNVUKLS0tIFh2bjRaT0ZHNUQ2M0FLa2NhSGpC
            WHR4U2VpeGVUa2pYUzlTK2FNTVFFRDgKRfPRRwCIas9RgXhLybaGUUdzMaof/1Y6
            kresU2mSRQqsC5Ntr76jnYxE2UtcH6YLeUpq3PGUFyVdAD/E52KvBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-19T16:57:25Z"
    mac: ENC[AES256_GCM,data:QzEh+PVGqKLB7o+uryOxqaU3FzFdXNLwLv2pcL+NwpuLUzaPO+Pr4RgHUiCMU/dZLL2abBQkD+MGsmWWjKuig7+u8FGyxMuUFCVCTSjF3mWhW4uqUaM6ptZXHvPN0emu1sh7FkeLEe5bEAQ8BrgUgbMUzJIh2QFWqZIed31XPcU=,iv:nDxvZo31PZQmRJwr8+ymv/0NhjFWO313CtyU5dOQgLE=,tag:DKEtbRQw+hO29R7GHaGFNg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
