---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-system-upgrade
  namespace: flux-system
spec:
  path: ./cluster/apps/system-upgrade/system-upgrade-controller/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-system-upgrade-config
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-system-upgrade
  path: ./cluster/apps/system-upgrade/system-upgrade-controller/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
