---
name: "Flux Diff"

on:
  pull_request:
    branches: ["main"]
    paths: ["**.yaml"]

jobs:
  flux-diff:
    name: Flux Diff
    permissions:
      contents: read
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path: ["cluster"]
        resource: ["helmrelease", "kustomization"]
    steps:
      # - name: Generate Token
      #   uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92 # v1.8.0
      #   id: generate-token
      #   with:
      #     app_id: "${{ secrets.BOT_APP_ID }}"
      #     private_key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@bda4c8187e436462be0d072e728b67afa215c593 # v2.6.3
      - uses: allenporter/flux-local/action/diff@42e5af6147d86834fe1ab51e8da9f7c14bf85246 # 7.5.6
        id: diff
        with:
          path: ${{ matrix.path }}
          resource: ${{ matrix.resource }}

      - name: Add comment
        uses: mshick/add-pr-comment@b8f338c590a895d50bcbfa6c5859251edc8952fc # v2
        if: ${{ steps.diff.outputs.diff != '' }}
        with:
          # repo-token: ${{ steps.generate-token.outputs.token }}
          message-id: ${{ matrix.path }}/${{ matrix.resource }}
          message-failure: Diff was not successful
          message: |
            ```diff
            ${{ steps.diff.outputs.diff }}
            ```
