---
name: Lint Markdown files on Pull Requests

on: # yamllint disable-line rule:truthy
  pull_request:
    paths:
      - "**.md"

jobs:
  markdownlint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - name: Get changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: shell
          filters: |
            markdown:
              - added|modified: "**.md"
      - name: Lint files
        if: ${{ steps.filter.outputs.markdown == 'true' }}
        uses: reviewdog/action-shellcheck@96fa305c16b0f9cc9b093af22dcd09de1c8f1c2d # v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          markdownlint_flags: "-c '.github/linters/.markdownlint.yaml' ${{ steps.filter.outputs.markdown_files }}"
